### ISSUE TITLE
User Defined GUID

### ISSUE THREAD

**Issue by ShayanFiroozi** [dotnet/WatsonTcp#264]
The **GUID** of both **Server** and **Client** are generated automatically which is not so ideal , in my scenario I need to set my own **GUID** to the both Server and Client in order to identify them when communicating and sending messages to each other.

Is this possible ?

**Comment by jchristn** [comment]
Hi @ShayanFiroozi this is an excellent request but unfortunately will require a pretty significant rework.  If you have a PR, I'd love to see it, otherwise I'll put it in my backlog.

**Comment by jchristn** [comment]
Hi @ShayanFiroozi I know it's been some time since you posted this issue, but I wanted to let you know this capability is now in.  Please see v6.0.2 in NuGet; there is an example in the README.  Cheers!
