### ISSUE TITLE
Please help with the method SyncRequestReceived 🙏🏼

### ISSUE THREAD

**Issue by SnowdenDev** [dotnet/WatsonTcp#275]
Hi everyone, I'm wondering if I can run this synchronous method asynchronously?
 private static SyncResponse SyncRequestReceived(SyncRequest request)
I would like the server to process them asynchronously, since data will be recorded and writing to multiple files in an async manner will be more optimal. If anyone knows, please ask for help.

**Comment by jchristn** [comment]
Hi @SnowdenDev thanks for your note, it's currently synchronous at this time.  If you'd like to submit a PR I'd be happy to integrate it!

**Comment by SnowdenDev** [comment]
**Please @jchristn , you needed an asynchronous SyncRequestReceived method! Can I create it on my own?**

**Comment by jchristn** [comment]
Hi @SnowdenDev please feel free to make a PR on this and I will integrate. Otherwise I will do my best to get to it this week. Thanks!

**Comment by SnowdenDev** [comment]
Hello @jchristn , thank you for your response, I am interested in creating the PR but I still do not understand what PR is, I am a little new to the platform! but without a doubt I would like to collaborate, WatsonTcp is something wonderful

**Comment by jchristn** [comment]
Hi @SnowdenDev I'm working on an update now that will include this :)

**Comment by jchristn** [comment]
Alright please check out v6.0.0 on NuGet and reopen if any issues!  Cheers and thanks for your patience!

**Comment by SnowdenDev** [comment]
@jchristn Good evening from here, really when I saw your answer I left everything and ran to the computer to check the version 6.0.0.0, I already have it installed but I can't find how to use SyncRequestRecived in an Async way? Am I forgetting something?, I attach an image,,,,
![image](https://github.com/dotnet/WatsonTcp/assets/124455295/a93e9298-5149-4600-8549-4bf576b177df)
This is the error of the attached code:

**Error CS0407 'Task<SyncResponse> Server.SyncRequestReceived(SyncRequest)' 
has an incorrect return type**

**Comment by SnowdenDev** [comment]
**I just found it, thank you very much, I love It**
![image](https://github.com/dotnet/WatsonTcp/assets/124455295/1cc68170-5693-4af1-920d-91ef9e6a5e46)
