### ISSUE TITLE
Issue reported by Sentry

### ISSUE THREAD

**Issue by wesoos** [dotnet/WatsonTcp#277]
Hello, I have Sentry hooked into one of my projects using WatsonTcp.  I'm seeing the following error reported somewhere in Watson.

async Task WatsonTcpClient.IdleServerMonitor(CancellationToken token)

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by jchristn** [comment]
Hi @wesoos I just published v6.0.5 which has try/catch inside of the IdleServerMonitor method.  Please re-open if the issue persists.
