### ISSUE TITLE
iOS TLS 1.3 - Security protocol is not supported.

### ISSUE THREAD

**Issue by hitchhiker** [dotnet/WatsonTcp#282]
I receive an error when using:

`WatsonTcpClient(host,port,path,password,TlsVersion.Tls13);`

 **System.PlatformNotSupportedException: The requested security protocol is not supported.**

Testing on iOS 17.3.1 (not AOT)

**Comment by jchristn** [comment]
Sorry for the delay @hitchhiker thank you for letting us know.  This is, unfortunately, something that would require an update on Microsoft's side; not something we can do anything about.
