### ISSUE TITLE
MessageBuilder: header partial read

### ISSUE THREAD

**Issue by zii-dmg** [dotnet/WatsonTcp#299]
https://github.com/dotnet/WatsonTcp/blob/49d796e4d794ae1f7e74c5778ae8afb73bb4947b/src/WatsonTcp/WatsonMessageBuilder.cs#L107

There is no check for read count so header can be read partially. Then array has zero bytes at end and check for zeros generates exception "Null header data indicates peer disconnected". There should be `while (readCount < 24)` loop. I think I got partial reads on real network because logs contains "Null header data indicates peer disconnected".

Also read can return 0 count for gracefully closed socket.

Line:
https://github.com/dotnet/WatsonTcp/blob/49d796e4d794ae1f7e74c5778ae8afb73bb4947b/src/WatsonTcp/WatsonMessageBuilder.cs#L130
Also should check for 0 count.

**Comment by sancheolz** [comment]
Related to https://github.com/dotnet/WatsonTcp/issues/263/.
I think the deadlock is happening there due to receiving an incomplete header. Setting `NoDelay = true` just hid the problem.

**Comment by jchristn** [comment]
Resolving in 6.0.8, uploading in a few moments.

**Comment by sancheolz** [comment]
After fix the bug is still happening.
Here my solution which works fine

```diff
--- /tmp/do2ngb_WatsonMessageBuilder.cs
+++ /tmp/j5qOgb_WatsonMessageBuilder.cs
@@ -104,7 +104,17 @@
             // {"len":0,"s":"Normal"}\r\n\r\n
             byte[] headerBytes = new byte[24];
 
-            await stream.ReadAsync(headerBytes, 0, 24, token).ConfigureAwait(false);
+            int totalBytesCount = 0;
+
+            while (totalBytesCount < 24)
+            {
+                int bytesCount = await stream.ReadAsync(headerBytes, totalBytesCount, 24 - totalBytesCount, token)
+                    .ConfigureAwait(false);
+                if (bytesCount == 0)
+                    break;
+                totalBytesCount += bytesCount;
+            }
+
             byte[] headerBuffer = new byte[1];
 
             while (true)
```
