### ISSUE TITLE
WatsonTcpServer v6.0.3 throws ArgumentException when disposed: "An item with the same key has already been added"

### ISSUE THREAD

**Issue by yallie** [dotnet/WatsonTcp#304]
Hello!

Not sure if it's relevant to issue #303, but sometimes I get another exception from the code below:

```csharp
var server = new WatsonTcpServer("127.0.0.1", 9000);
server.Events.MessageReceived += (s, e) => Console.WriteLine("srecv");
server.Start();

var client = new WatsonTcpClient("127.0.0.1", 9000);
client.Events.MessageReceived += (s, e) => Console.WriteLine("crecv");
client.Connect();

await client.SendAsync("aaa");
await Task.Delay(100);
server.Dispose();
```

```
System.AggregateException : One or more errors occurred.
---- System.ArgumentException : An item with the same key has already been added. Key: be8924c2-0945-4b7f-be64-2996d62d9b56

Stack Trace: 
Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
Task.Wait()
WatsonTcpServer.Dispose(Boolean disposing)
WatsonTcpServer.Dispose()
RegressionTests.WatsonTcpThrowsCanceledExceptionOnDispose() line 29
<>c.<ThrowAsync>b__128_0(Object state)
----- Inner Stack Trace -----
Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
Dictionary`2.Add(TKey key, TValue value)
ClientMetadataManager.AddClientKicked(Guid guid)
WatsonTcpServer.DisconnectClientAsync(Guid guid, MessageStatus status, Boolean sendNotice, CancellationToken token)
WatsonTcpServer.DisconnectClientsAsync(MessageStatus status, Boolean sendNotice, CancellationToken token)
```

The error originates here: [WatsonTcpServer.cs, line 572](https://github.com/dotnet/WatsonTcp/blob/49d796e4d794ae1f7e74c5778ae8afb73bb4947b/src/WatsonTcp/WatsonTcpServer.cs#L572)

```csharp
if (!_ClientManager.ExistsClientTimedout(guid)) _ClientManager.AddClientKicked(guid);
```

The problem is introduced in this commit: [NuGet v6.0.3, internal refactor e.g. ClientManager)](https://github.com/dotnet/WatsonTcp/commit/d4b99d3628dcd5de19d796c5c57411b23fc2765f#diff-34d861fdbc7300d1f93235769aae35636a6f4ba7e3a8e867dbae1fe142f5ac52R694).

Older versions use `ConcurrentDictionary` instances for clients, last seen, kicked, etc:

```csharp
private ConcurrentDictionary<Guid, DateTime> _UnauthenticatedClients = new ConcurrentDictionary<Guid, DateTime>();
private ConcurrentDictionary<Guid, ClientMetadata> _Clients = new ConcurrentDictionary<Guid, ClientMetadata>();
private ConcurrentDictionary<Guid, DateTime> _ClientsLastSeen = new ConcurrentDictionary<Guid, DateTime>();
private ConcurrentDictionary<Guid, DateTime> _ClientsKicked = new ConcurrentDictionary<Guid, DateTime>();
private ConcurrentDictionary<Guid, DateTime> _ClientsTimedout = new ConcurrentDictionary<Guid, DateTime>();
```

New refactored version use ordinal `Dictionary` instances protected by locks in [ClientMetadataManager.cs](https://github.com/dotnet/WatsonTcp/blob/49d796e4d794ae1f7e74c5778ae8afb73bb4947b/src/WatsonTcp/ClientMetadataManager.cs#L277):

```csharp
private readonly object _ClientsKickedLock = new object();
private Dictionary<Guid, DateTime> _ClientsKicked = new Dictionary<Guid, DateTime>();
...
internal void AddClientKicked(Guid guid)
{
    lock (_ClientsKickedLock)
    {
        _ClientsKicked.Add(guid, DateTime.UtcNow);
    }
}
```

Older versions use [_ClientsKicked.TryAdd](https://github.com/dotnet/WatsonTcp/blob/0a06c194ca17faa3d04827ea9ee104e835a9d0f8/src/WatsonTcp/WatsonTcpServer.cs#L696C17-L696C103) which is thread-safe by design:

```csharp
if (!_ClientsTimedout.ContainsKey(guid)) _ClientsKicked.TryAdd(guid, DateTime.UtcNow);
```

Can we revert it back to `ConcurrentDictionary`?

**Comment by yallie** [comment]
Occurs from time to time in our unit tests here on [Github Actions](https://github.com/theRainbird/CoreRemoting/actions/runs/12300577226/job/34330031711)
since we updated WatsonTcp dependency to the latest version:

![Image](https://github.com/user-attachments/assets/b1292168-f23b-4138-be76-064fe79b6700)

**Comment by jchristn** [comment]
Added checks for this inside of lock statements within ClientMetadataManager, will post 6.0.8 in a few moments with the fix.
